version: '3.9'

services:
  backend:
    build: ./backend
    container_name: vpn-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: vpn-frontend

  nginx:
    build: ./nginx
    container_name: vpn-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  db:
    image: postgres:15-alpine
    container_name: vpn-db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data