volumes:
  wg_configs:
  db_data:

services:
  backend:
    build: ./backend
    container_name: vpn-backend
    env_file:
      - .env
    volumes:
      - wg_configs:/app/wg_configs
      - db_data:/app/db
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: vpn-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vpn-frontend
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: vpn-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  amnezia:
    build: ./amnezia-container
    container_name: amnezia
    env_file:
      - .env
    volumes:
      - wg_configs:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "${PORT}:${PORT}/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped
